### ISSUE TITLE
Рекомендации генерации поля Id

### ISSUE THREAD

**Issue by brown-aleks** [nikysn/ToDoList-PlayerDataBase#2]
https://github.com/nikysn/ToDoList-PlayerDataBase/blob/d2a33ba832e8c5b47d9d74242dc4c28cf9a913b8/PlayerDataBase.CLI/Database.cs#L16

На мой взгляд необходимо продумать более надёжный способ генерации уникального значения поля **Id**. Так как:
* Ранее когда либо сгенерированный **Id** не должен повторяться у вновь созданных экземпляров. Даже если каки либо экземпляры были удалены, и якобы их занимаемый Id освободился. **Id** не должен воскреснуть.
* Логика генерации уникального поля **Id**, которое в этом проекте указывает на уникальность экземпляра класса **Player**, я бы рекомендовал перенести в варианты перегрузки конструкторов того же класса **Player**

**Comment by IlyaEliseev** [comment]
> * Логика генерации уникального поля **Id**, которое в этом проекте указывает на уникальность экземпляра класса **Player**, я бы рекомендовал перенести в варианты перегрузки конструкторов того же класса **Player**

Не стоит приносить в бизнес логику зависимость от хранилища. Иначе, когда мы поменяем способ хранения данных, последствия будут непредсказуемыми:)

```c#
private int CreateId()
    {
        int id = 1;
        var players = GetPlayers();

        for (int i = 1; i <= players.Length; i++) //если убрать этот цикл ничего не изменится
        {
            for (int j = 0; j < players.Length; j++)
            {
                if (id == players[j].Id)
                {
                    id++;
                    i--;//тут нужно пояснение ))
                }
            }
        }
        return players.Length == 0 ? 1 : id;
    }
```
А так интересная задумка с повторным использованием id удаленных сущностей.

**Comment by brown-aleks** [comment]
> Не стоит приносить в бизнес логику зависимость от хранилища. Иначе, когда мы поменяем способ хранения данных, последствия будут непредсказуемыми:)

Конечно, тут есть твоя правда. =) Прост как бы автор в самом начале своего развития. И как мне кажется понятия об разделении логики приложения по слоям, это ещё ему рановато.
После того как хоть немного научился плести лапшичный код, нужно шишек набить с конструкторами. Далее уже смотреть на зависимости и их классификации. Вот после этого можно поговорить про слои приложения. =)
